### ISSUE TITLE
Error when transcribe

### ISSUE THREAD

**Issue by LiveRock** [williamidt/whisper_dart_my_first_test_v2#1]
I got this error:

flutter: Invalid argument(s): Failed to lookup symbol 'request': dlsym(RTLD_DEFAULT, request): symbol not found
flutter: {"@type":"error","message":"Invalid argument(s): Failed to lookup symbol 'request': dlsym(RTLD_DEFAULT, request): symbol not found"}
flutter: Invalid argument(s): Failed to lookup symbol 'request': dlsym(RTLD_DEFAULT, request): symbol not found
flutter: {"@type":"error","message":"Invalid argument(s): Failed to lookup symbol 'request': dlsym(RTLD_DEFAULT, request): symbol not found"}

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'Future<dynamic>' is not a subtype of type 'String'

When the exception was thrown, this was the stack:
#0      _HomePageState.build.<anonymous closure>.<anonymous closure> (package:whisper_dart_my_first_test_v2/pages/home_page.dart:82:19)
#1      State.setState (package:flutter/src/widgets/framework.dart:1133:30)
#2      _HomePageState.build.<anonymous closure> (package:whisper_dart_my_first_test_v2/pages/home_page.dart:80:17)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1096:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#21     _invoke1 (dart:ui/hooks.dart:164:13)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#bf0e6
════════════════════════════════════════════════════════════════════════════════════════════════════

Anyway to fix?

**Comment by williamidt** [comment]
Hi @LiveRock , 

I updated code to whisper_dart: ^0.0.10 and included getx (simple form).. please clone git again..
I only tested in android X86_64..  You tried in other plataform (windows, linux, iphone) before you have that to compile libwhisper.so and put file into jniLibs... 

Also update readme.me, i hope it helps in some way... I did running now in android and its okay.. (see picture in readme).. only problem is that take a long time to transcribe. I'm trying to understand why...

I intend to test whisper with go module to see if more fast running

tmj

**Comment by LiveRock** [comment]
Do you have the .so file? When I compile, I only get a libwhisper.dylib file instead of a .so file

I followed the instructions at
https://github.com/azkadev/whisper_dart/tree/main/native_lib

**Comment by williamidt** [comment]
Hi @LiveRock, yes I got it!
.
So, correcting an information. For Android it is .so, for Windows it is .dll and Mac or IOS is .dylib
.
.
You must place the .dylib file in the project as below. Try to understand this code. There is also a link to the website. I believe that if you just put the file in the correct directory on the mac and try to run it, the problem will be solved
.
Link https://docs.flutter.dev/development/platform-integration/macos/c-interop
.
Compiled (dynamic) library (macOS)
To add a closed source library to a [Flutter macOS Desktop](https://docs.flutter.dev/desktop) application, use the following instructions:

.
Follow the Flutter desktop instructions to create a Flutter desktop app.
Open your app/macos/Runner.xcworkspace in Xcode.
Drag your precompiled library (libyourlibrary.dylib) to Runner/Frameworks.
Click on Runner and go to the Build Phases tab.
Drag libyourlibrary.dylib to the Copy Bundle Resources list.
Under Embed Libraries, check Code Sign on Copy.
Under Link binary with libraries, set the status to Optional. (We use dynamic links, no need to link statically.)
Click on Runner and go to the General tab.
Drag libyourlibrary.dylib to the Frameworks, Libraries and Embedded Content list.
Select Embed and Sign.
Click on Runner and go to the Build Settings tab.
In the Search Paths section, set the Library Search Paths to include the path where libyourlibrary.dylib is located.
Edit lib/main.dart.
Use DynamicLibrary.open('libyourlibrary.dylib') to dynamically link to symbols.
Call your native function somewhere in a widget.
Run flutter run and check if your native function is called.
Run flutter build macos to create a standalone release version of your app.
.
..
In the whisper_dart.dart package, if it does not run correctly, check if it is necessary to comment if (Platform.isIOS || Platform.isMacOS) {
           return DynamicLibrary.process();
         } other {


..
       DynamicLibrary openLib({
         String? whisperLib,
         whisperLib ??= whisper_lib;
        if (Platform.isIOS || Platform.isMacOS) {
           return DynamicLibrary.process();
         } other {
           return DynamicLibrary.open(whisperLib);
         }
       }

..
tmj




.

**Comment by LiveRock** [comment]
I followed the instructions and now I cannot build and run on macOS.

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-0006199E0ED8801E }
{ platform:macOS, arch:x86_64, id:00006000-0006199E0ED8801E }
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftCoreMedia'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCoreAudio'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftXPC'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
ld: warning: Could not find or use auto-linked library 'swiftIOKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftAppKit'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
Undefined symbols for architecture arm64:
  "_$s10ObjectiveC22_convertBoolToObjCBoolyAA0eF0VSbF", referenced from:
      _$s29whisper_dart_my_first_test_v211AppDelegateC47applicationShouldTerminateAfterLastWindowClosedySbSo13NSApplicationCFTo in AppDelegate.o
  "_$s10ObjectiveC22_convertObjCBoolToBoolySbAA0cD0VF", referenced from:
      _$s29whisper_dart_my_first_test_v217MainFlutterWindowC11contentRect9styleMask7backing5deferACSo6CGRectV_So013NSWindowStyleM0VSo18NSBackingStoreTypeVSbtcfcTo in MainFlutterWindow.o
  "_$sBOWV", referenced from:
      _$s29whisper_dart_my_first_test_v217MainFlutterWindowCMf in MainFlutterWindow.o
      _$s29whisper_dart_my_first_test_v211AppDelegateCMf in AppDelegate.o
  "__swift_FORCE_LOAD_$_swiftAppKit", referenced from:
      __swift_FORCE_LOAD_$_swiftAppKit_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftAppKit_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftAppKit_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftAppKit_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftCoreAudio", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreAudio_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftCoreAudio_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCoreAudio_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreAudio_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftCoreGraphics", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreGraphics_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftCoreGraphics_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCoreGraphics_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreGraphics_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreImage_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftCoreImage_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCoreImage_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftCoreMedia", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreMedia_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftCoreMedia_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCoreMedia_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMedia_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftDarwin_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftDarwin_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
      __swift_FORCE_LOAD_$_swiftDispatch_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftDispatch_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftDispatch_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftIOKit", referenced from:
      __swift_FORCE_LOAD_$_swiftIOKit_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftIOKit_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftIOKit_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftIOKit_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
      __swift_FORCE_LOAD_$_swiftMetal_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftMetal_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftMetal_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftQuartzCore", referenced from:
      __swift_FORCE_LOAD_$_swiftQuartzCore_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftQuartzCore_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftQuartzCore_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftQuartzCore_$_whisper_dart_my_first_test_v2)
  "__swift_FORCE_LOAD_$_swiftXPC", referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_whisper_dart_my_first_test_v2 in MainFlutterWindow.o
      __swift_FORCE_LOAD_$_swiftXPC_$_whisper_dart_my_first_test_v2 in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftXPC_$_whisper_dart_my_first_test_v2 in GeneratedPluginRegistrant.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftXPC_$_whisper_dart_my_first_test_v2)
  "_swift_getObjCClassFromMetadata", referenced from:
      _$sSo21FlutterViewControllerCABycfC in MainFlutterWindow.o
  "_swift_getObjCClassMetadata", referenced from:
      _$sSo21FlutterViewControllerCMa in MainFlutterWindow.o
  "_swift_unknownObjectRelease", referenced from:
      _$s29whisper_dart_my_first_test_v217MainFlutterWindowC12awakeFromNibyyF in MainFlutterWindow.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

Building macOS application...    
```

Tried a few times but without success.

**Comment by williamidt** [comment]
Hi Peter Lum, how are you? I hope well ...

I don't have Mac to compile it, so it's hard to help you. If you want you can send the .dylib file that I can see if I can help you here. Just not guarantee that it will be fast because I have several things to do so I do not have much time for it ...

I don't know if you can send .. if you can't .. send it to my email xxxxxxx (for security i removed my email address)

If you need this package for some job. My suggestion is that you try to find some developer who use Mac to help you or try again .. on the internet there are several posts on how to implement a C ++ library for flutter using mac iOS .. try to survey ..

I had not gotten first .. I had to try several to be able to run .. still in my view she is slow in transcription ..

I will try to test with the GO Whisper library for the Flutter .. to see if the speed better.

Ok let's talk, a hug

Tmj

**Comment by LiveRock** [comment]
Thank you William. I sent eh dylib to you via email as this platform does not allow me to.

**Comment by williamidt** [comment]
Hi Peter,

Were you able to proceed with error?

So... I saw some discussions about running on Mac iphone... maybe it will help you

I decided not to move forward with implementing translated speech in offline mode in my application.

I think this package is new yet not safe for that.  Better testing is needed.

tmj
